### ISSUE TITLE
Images missing from "The IDE Divide" post

### ISSUE THREAD

**Issue by ncoghlan** [osteele/blog.osteele.com#1]
Hi, I'm a huge fan of the post you wrote years ago about "The IDE Divide", and still regularly share it with folks when it seems appropriate: http://blog.osteele.com/posts/2004/11/ides

Unfortunately, the image links are currently 404'ing, and l couldn't see any obvious way of fixing that when looking at the blog repository (hence the issue, rather than a PR).

**Comment by osteele** [comment]
Thanks, this should be fixed now.

**Comment by ncoghlan** [comment]
Indeed it is - thank you!
